/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.giovaneneves7.musicplayer.view;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author curso
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        
        pnlSideMenuBackground.setVisible(false);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlSideMenuBackground = new javax.swing.JPanel();
        pnlBackgroundItemSideMenu1 = new javax.swing.JPanel();
        lblItemSideMenu1 = new javax.swing.JLabel();
        pnlBackgroundItemSideMenu2 = new javax.swing.JPanel();
        lblItemSideMenu2 = new javax.swing.JLabel();
        pnlBackgroundItemSideMenu3 = new javax.swing.JPanel();
        lblItemSideMenu3 = new javax.swing.JLabel();
        btnAbrirMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pnlBackground.setBackground(new java.awt.Color(51, 51, 51));
        pnlBackground.setLayout(null);

        pnlSideMenuBackground.setBackground(new java.awt.Color(0, 0, 0));

        pnlBackgroundItemSideMenu1.setBackground(new java.awt.Color(0, 0, 0));
        pnlBackgroundItemSideMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBackgroundItemSideMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBackgroundItemSideMenu1MouseExited(evt);
            }
        });

        lblItemSideMenu1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblItemSideMenu1.setForeground(new java.awt.Color(255, 255, 255));
        lblItemSideMenu1.setText("Home");
        lblItemSideMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblItemSideMenu1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundItemSideMenu1Layout = new javax.swing.GroupLayout(pnlBackgroundItemSideMenu1);
        pnlBackgroundItemSideMenu1.setLayout(pnlBackgroundItemSideMenu1Layout);
        pnlBackgroundItemSideMenu1Layout.setHorizontalGroup(
            pnlBackgroundItemSideMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundItemSideMenu1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblItemSideMenu1)
                .addGap(44, 44, 44))
        );
        pnlBackgroundItemSideMenu1Layout.setVerticalGroup(
            pnlBackgroundItemSideMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundItemSideMenu1Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(lblItemSideMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlBackgroundItemSideMenu2.setBackground(new java.awt.Color(0, 0, 0));
        pnlBackgroundItemSideMenu2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBackgroundItemSideMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBackgroundItemSideMenu2MouseClicked(evt);
            }
        });

        lblItemSideMenu2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblItemSideMenu2.setForeground(new java.awt.Color(255, 255, 255));
        lblItemSideMenu2.setText("Minhas Músicas");
        lblItemSideMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItemSideMenu2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblItemSideMenu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblItemSideMenu2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundItemSideMenu2Layout = new javax.swing.GroupLayout(pnlBackgroundItemSideMenu2);
        pnlBackgroundItemSideMenu2.setLayout(pnlBackgroundItemSideMenu2Layout);
        pnlBackgroundItemSideMenu2Layout.setHorizontalGroup(
            pnlBackgroundItemSideMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundItemSideMenu2Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(lblItemSideMenu2)
                .addGap(16, 16, 16))
        );
        pnlBackgroundItemSideMenu2Layout.setVerticalGroup(
            pnlBackgroundItemSideMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundItemSideMenu2Layout.createSequentialGroup()
                .addComponent(lblItemSideMenu2)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pnlBackgroundItemSideMenu3.setBackground(new java.awt.Color(0, 0, 0));
        pnlBackgroundItemSideMenu3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblItemSideMenu3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblItemSideMenu3.setForeground(new java.awt.Color(255, 255, 255));
        lblItemSideMenu3.setText("Sair");
        lblItemSideMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblItemSideMenu3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundItemSideMenu3Layout = new javax.swing.GroupLayout(pnlBackgroundItemSideMenu3);
        pnlBackgroundItemSideMenu3.setLayout(pnlBackgroundItemSideMenu3Layout);
        pnlBackgroundItemSideMenu3Layout.setHorizontalGroup(
            pnlBackgroundItemSideMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundItemSideMenu3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblItemSideMenu3)
                .addGap(44, 44, 44))
        );
        pnlBackgroundItemSideMenu3Layout.setVerticalGroup(
            pnlBackgroundItemSideMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundItemSideMenu3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(lblItemSideMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlSideMenuBackgroundLayout = new javax.swing.GroupLayout(pnlSideMenuBackground);
        pnlSideMenuBackground.setLayout(pnlSideMenuBackgroundLayout);
        pnlSideMenuBackgroundLayout.setHorizontalGroup(
            pnlSideMenuBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideMenuBackgroundLayout.createSequentialGroup()
                .addGroup(pnlSideMenuBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBackgroundItemSideMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlSideMenuBackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSideMenuBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlBackgroundItemSideMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlBackgroundItemSideMenu3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlSideMenuBackgroundLayout.setVerticalGroup(
            pnlSideMenuBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSideMenuBackgroundLayout.createSequentialGroup()
                .addComponent(pnlBackgroundItemSideMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBackgroundItemSideMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(pnlBackgroundItemSideMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlBackground.add(pnlSideMenuBackground);
        pnlSideMenuBackground.setBounds(10, 10, 120, 420);

        btnAbrirMenu.setBackground(new java.awt.Color(51, 51, 51));
        btnAbrirMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menux24.png"))); // NOI18N
        btnAbrirMenu.setToolTipText("");
        btnAbrirMenu.setBorderPainted(false);
        btnAbrirMenu.setContentAreaFilled(false);
        btnAbrirMenu.setFocusPainted(false);
        btnAbrirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirMenuActionPerformed(evt);
            }
        });
        pnlBackground.add(btnAbrirMenu);
        btnAbrirMenu.setBounds(10, 10, 50, 30);

        getContentPane().add(pnlBackground);
        pnlBackground.setBounds(0, 0, 790, 430);

        setSize(new java.awt.Dimension(803, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirMenuActionPerformed
        pnlSideMenuBackground.setVisible(true);
    }//GEN-LAST:event_btnAbrirMenuActionPerformed

    private void lblItemSideMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemSideMenu3MouseClicked
        pnlSideMenuBackground.setVisible(false);
    }//GEN-LAST:event_lblItemSideMenu3MouseClicked

    private void lblItemSideMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemSideMenu1MouseEntered

      changeElementColor(lblItemSideMenu1, Color.yellow);
      
    }//GEN-LAST:event_lblItemSideMenu1MouseEntered

    private void pnlBackgroundItemSideMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBackgroundItemSideMenu1MouseExited
        changeElementColor(lblItemSideMenu1, Color.white);
    }//GEN-LAST:event_pnlBackgroundItemSideMenu1MouseExited

    private void pnlBackgroundItemSideMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBackgroundItemSideMenu2MouseClicked

    }//GEN-LAST:event_pnlBackgroundItemSideMenu2MouseClicked

    private void lblItemSideMenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemSideMenu2MouseExited
       
        changeElementColor(lblItemSideMenu2, Color.white);
       
    }//GEN-LAST:event_lblItemSideMenu2MouseExited

    private void lblItemSideMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemSideMenu2MouseClicked
        new MinhasMusicasView().setVisible(true);
    }//GEN-LAST:event_lblItemSideMenu2MouseClicked

    private void lblItemSideMenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblItemSideMenu2MouseEntered
        changeElementColor(lblItemSideMenu2, Color.yellow);
    }//GEN-LAST:event_lblItemSideMenu2MouseEntered

    private void changeElementColor(JLabel element, Color color){
        
        element.setForeground(color);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirMenu;
    private javax.swing.JLabel lblItemSideMenu1;
    private javax.swing.JLabel lblItemSideMenu2;
    private javax.swing.JLabel lblItemSideMenu3;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlBackgroundItemSideMenu1;
    private javax.swing.JPanel pnlBackgroundItemSideMenu2;
    private javax.swing.JPanel pnlBackgroundItemSideMenu3;
    private javax.swing.JPanel pnlSideMenuBackground;
    // End of variables declaration//GEN-END:variables
}


