/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.giovaneneves7.musicplayer.view;

import com.mpatric.mp3agic.Mp3File;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;

import javax.swing.JOptionPane;

import java.util.List;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JScrollPane;

/**
 *
 * @author curso
 */
public class MinhasMusicasView extends javax.swing.JFrame {

    //    C:\\Users\\${USERNAME}\\Music
    private String caminhoPasta = "C:\\Users\\curso\\Music";
    private File diretorio = new File(caminhoPasta);
    private DefaultListModel<String> listModel = new DefaultListModel<>();
    private JList<String> musicasList = new JList<>(listModel);
    private List<File> musicas = new ArrayList<>();
    /**
     * Creates new form MinhasMusicasView
     */
    public MinhasMusicasView() {
        initComponents();
        verificarPasta();
        createUI();
  
    }
    
    private void createUI() {
        pnlMusicas.setLayout(new BorderLayout());

        JScrollPane scrollPane = new JScrollPane(musicasList);
        pnlMusicas.add(scrollPane, BorderLayout.CENTER);

        btnPlay.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selectedIndex = musicasList.getSelectedIndex();
                if (selectedIndex >= 0) {
                    File selectedFile = musicas.get(selectedIndex);
                    play(selectedFile);
                }
            }
        });

        pnlMusicas.add(btnPlay, BorderLayout.SOUTH);
    }

    private void verificarPasta(){
        
        if(!diretorio.isDirectory()){
            
            JOptionPane.showMessageDialog(null, "A pasta especificada não existe: ".concat(caminhoPasta), "Diretório não encontrado", JOptionPane.ERROR_MESSAGE);
            return;
                        
        }
        
        for(File arqv : diretorio.listFiles()){
            
            if(arqv.isFile() && arqv.getName().toLowerCase().endsWith(".mp3")){
                musicas.add(arqv);
                listModel.addElement(arqv.getName());
            }
            
        }
        
    }
    
    public void play(File arquivo){
        if(musicas.isEmpty()){
            System.out.println("Nenhuma música a ser tocada");
        }
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        pnlMusicas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBackground.setBackground(new java.awt.Color(51, 51, 51));
        pnlBackground.setLayout(null);

        pnlMusicas.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlMusicasLayout = new javax.swing.GroupLayout(pnlMusicas);
        pnlMusicas.setLayout(pnlMusicasLayout);
        pnlMusicasLayout.setHorizontalGroup(
            pnlMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        pnlMusicasLayout.setVerticalGroup(
            pnlMusicasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlBackground.add(pnlMusicas);
        pnlMusicas.setBounds(10, 120, 770, 100);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recém adicionadas:");
        pnlBackground.add(jLabel1);
        jLabel1.setBounds(10, 90, 150, 30);

        btnPlay.setBackground(new java.awt.Color(0, 204, 51));
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        pnlBackground.add(btnPlay);
        btnPlay.setBounds(330, 230, 75, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(803, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        int selectedIndex = musicasList.getSelectedIndex();
        if (selectedIndex >= 0) {
            File selectedFile = musicas.get(selectedIndex);
            play(selectedFile);
        }
    }//GEN-LAST:event_btnPlayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MinhasMusicasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MinhasMusicasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MinhasMusicasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MinhasMusicasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MinhasMusicasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlMusicas;
    // End of variables declaration//GEN-END:variables
}
/*try {
            // Crie um processo usando o comando desejado
            ProcessBuilder processBuilder = new ProcessBuilder("cmd.exe", "/c", "dir"); // Exemplo: listando diretório no Windows

            // Configure o diretório de trabalho, se necessário
            // processBuilder.directory(new File("caminho/do/diretorio"));

            // Inicie o processo
            Process processo = processBuilder.start();

            // Leia a saída do processo
            BufferedReader leitorDeSaida = new BufferedReader(new InputStreamReader(processo.getInputStream()));
            String linha;
            while ((linha = leitorDeSaida.readLine()) != null) {
                System.out.println(linha);
            }

            // Espere o processo terminar
            int codigoDeSaida = processo.waitFor();

            System.out.println("Comando executado com código de saída: " + codigoDeSaida);

        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }*/